from __future__ import annotations

import argparse
import re
from datetime import datetime
from pathlib import Path


def slug(name: str) -> str:
    s = name.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    s = re.sub(r"-+", "-", s)
    return s


def normalize_display_name(name: str) -> str:
    # Target the mojibake patterns we have already seen in repo artifacts.
    # Note: this is intentionally narrow; if new patterns appear, extend mapping.
    replacements = {
        "Linked in Profile - Andr� Colleague-I.pdf": "Linked in Profile - André Colleague-I.pdf",
        "Andr� Colleague-I": "André Colleague-I",
        "Ferr�o": "Ferrão",
        "Re-run de pool sync apos": "Re-run de pool sync após",
        "automacao": "automaçao",
        "automa��o": "automaçao",
    }
    for k, v in replacements.items():
        name = name.replace(k, v)
    return name


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--date", default=None, help="YYYY-MM-DD (default: today)")
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    team_dir = repo_root / "docs" / "private" / "team_info"
    cand_dir = repo_root / "docs" / "private" / "commercial" / "candidates"
    out_dir = repo_root / "docs" / "private" / "commercial"

    if args.date:
        date_stamp = args.date
    else:
        date_stamp = datetime.now().strftime("%Y-%m-%d")

    out_path = out_dir / f"POOL_SYNC_SNAPSHOT_{date_stamp}.md"

    pdfs = sorted(team_dir.glob("*.pdf"))

    rows: list[tuple[str, str, str, str]] = []
    counts = {"OK": 0, "PARTIAL": 0, "MISSING": 0}

    for pdf in pdfs:
        s = slug(pdf.stem)
        pt = cand_dir / f"{s}.pt_BR.md"
        en = cand_dir / f"{s}.md"
        pt_ok = pt.exists()
        en_ok = en.exists()
        if pt_ok and en_ok:
            status = "OK"
        elif pt_ok or en_ok:
            status = "PARTIAL"
        else:
            status = "MISSING"

        counts[status] += 1
        rows.append(
            (
                normalize_display_name(pdf.name),
                pt.name if pt_ok else "(not found)",
                en.name if en_ok else "(not found)",
                status,
            )
        )

    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines: list[str] = []
    lines.append("# Pool sync snapshot (weekly audit)")
    lines.append("")
    lines.append(f"Timestamp: {ts}")
    lines.append("")
    lines.append("Source folders checked:")
    lines.append("")
    lines.append("- `docs/private/team_info` (PDF inputs)")
    lines.append("- `docs/private/commercial/candidates` (dossier outputs)")
    lines.append("")
    lines.append("## Short table (PDF -> dossiers -> status)")
    lines.append("")
    lines.append("| PDF input | Dossier pt-BR | Dossier EN | Status |")
    lines.append("| --- | --- | --- | --- |")
    for pdf_name, pt_name, en_name, status in rows:
        lines.append(f"| `{pdf_name}` | `{pt_name}` | `{en_name}` | **{status}** |")

    lines.append("")
    lines.append("## Summary")
    lines.append(f"- OK: {counts['OK']}")
    lines.append(f"- PARTIAL: {counts['PARTIAL']}")
    lines.append(f"- MISSING: {counts['MISSING']}")
    lines.append("")
    lines.append("## Notes")
    lines.append("- Auto-generated by `scripts/generate_pool_sync_snapshot.py`.")
    lines.append("")
    lines.append("## Next actions")
    lines.append(
        "1. If MISSING/PARTIAL exists, run: `talent-dossier next --advisor-remote --caution` (adjust flags as needed)."
    )

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote: {out_path}")


if __name__ == "__main__":
    main()
